version: '2'
services:
  spark-master:
    build:
      context: ./docker/spark
      dockerfile: Dockerfile
#    command: python app/main.py
    command: /usr/spark/bin/spark-class org.apache.spark.deploy.master.Master -h spark-master
    hostname: spark-master
    container_name: spark-master
    networks:
      - spark
    environment:
      MASTER: spark://spark-master:7077
      SPARK_PUBLIC_DNS: localhost
    volumes:
      - ./app:/app
      - ./resources:/resources
    expose:
      - 7001
      - 7002
      - 7003
      - 7004
      - 7005
      - 7006
      - 7077
      - 6066
    ports:
        - 4040:4040
        - 6066:6066
        - 7077:7077
        - 8080:8080
  spark-worker:
    build:
      context: ./docker/spark
      dockerfile: Dockerfile
    command: /usr/spark/bin/spark-class org.apache.spark.deploy.worker.Worker spark://spark-master:7077
    hostname: spark-worker
    networks:
      - spark
    environment:
      SPARK_WORKER_CORES: 1
      SPARK_WORKER_MEMORY: 1g
      SPARK_PUBLIC_DNS: localhost
    links:
      - spark-master
    volumes:
      - ./app:/app
      - ./resources:/resources
networks:
  spark:
    driver: bridge